### ISSUE TITLE
sync with video

### ISSUE THREAD

**Issue by camjac251** [ahabyss/TwitchChatReplay#1]
Would it be possible to be able to sync chat logs to a downloaded stream locally. Being able to say use streamlink to record the livestream to a file but also record the chat for it as well and be able to sync them up later with scrubbing support?

I was able to find this https://github.com/dekuNukem/Twitch_Chatlogs/tree/master/comment_logger since overrustle only logs channels with high follower counts.

**Comment by ahabyss** [comment]
Yes it is quite possible.  I haven't looked into the Twitch_Chatlogs project, but I'm sure you could use it. To make syncing easiest make sure you save a timestamp of each chat message, and save a timestamp when you begin recording the livestream with streamlink.

This project would be much easier if i had saved an exact timestamp when each episode began.

**Comment by camjac251** [comment]
Did you find a way to get the timestamps?

**Comment by ahabyss** [comment]
No, unfortunately I have to estimate using cues from chat / vods.
