### ISSUE TITLE
Anne Happy! not working.

### ISSUE THREAD

**Issue by Skyjersey** [ahabyss/TwitchChatReplay#2]
Only shows episode 1 and there is no text when I press play.

**Comment by ahabyss** [comment]
Anne Happy is one of the remaining shows I need to process.  This anime is non-trivial because I don't have vods for episodes 6 onward, and the mid-episode breaks don't have a consistent timing.

**Comment by ahabyss** [comment]
Anne Happy! is in the latest update.
